user nginx;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    server_tokens off;
    keepalive_timeout 65;
    client_header_timeout 15s;
    client_body_timeout 60s;
    send_timeout 60s;
    client_max_body_size 27M;
    log_format safe '$remote_addr - $request_id [$time_local] '
                    '"$request_method $uri $server_protocol" $status $body_bytes_sent '
                    '"$http_user_agent"';
    access_log /dev/stdout safe;
    error_log /dev/stderr warn;

    server {
        listen 8080 default_server;
        listen [::]:8080 default_server;
        server_name _;
        root /var/www/html/public;

        index index.php index.html;
        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        error_page 404 /index.php;

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param HTTP_PROXY "";
            fastcgi_read_timeout 120s;
            include fastcgi_params;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
